name: Add Patience Quotes to PRs

on:
  pull_request:
    types:
      - opened

jobs:
  add-quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Random Quote
        id: random-quote
        run: |
          echo "::set-output name=quote::$(curl -s https://api.quotable.io/random?tags=patience | jq -r '.content')"
